### PR TITLE
Bugfix for BTS-673

### LINKED ISSUE #15107: Discrepancy in records fetched between DB UI and Foxx _query method: Arango v3.7.15
## My Environment

* __ArangoDB Version__:       3.7.15
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:      Single Server
* __Deployment Strategy__:   ArangoDB Starter (on DEV local) | ArangoDB Starter in Docker (on TEST, UAT, PRD Environment)
* __Configuration__:               
* __Infrastructure__:                own
* __Operating System__:        Windows 10 (on DEV local) | Ubuntu 16.04 (on TEST, UAT, PRD Environment)
* __Total RAM in your machine__:        16 GB (on DEV local) | 62GB n PRD
* __Disks in use__:        
       

## Component, Query & Data

__Affected feature__:
Foxx | AQL query using web interface

__AQL query (if applicable)__:
Attached simplified query 
[simplified_evo_query.txt](https://github.com/arangodb/arangodb/files/7526863/simplified_evo_query.txt)

BindParam for simplified query:
[simplified_evo_bindParam.txt](https://github.com/arangodb/arangodb/files/7526865/simplified_evo_bindParam.txt)

__AQL explain (if applicable)__:
Attached aql execution plan
[simplified_evo_exec_plan.txt](https://github.com/arangodb/arangodb/files/7526877/simplified_evo_exec_plan.txt)

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Execute the attached simplified query on Arango web interface, Note the total number of records retrieved
2. Execute the same query from FOXX using db._query method, Capture total number of records retrieved

Following are readings noted in foxx response: 

```
"_countTotal": 6025,
"_countQuery": 6025,
"_skip": 0,
"_limit": null,
"_cached": false,
"_extra": {
    "stats": {
        "writesExecuted": 0,
        "writesIgnored": 0,
        "scannedFull": 9464,
        "scannedIndex": 0,
        "filtered": 275283,
        "httpRequests": 0,
        "executionTime": 1.8366911000339314,
        "peakMemoryUsage": 11007878
    },
    "warnings": []
},
"_current": 0,
"_stop": 6025
}
```
When used "fullCount" option in AQL:
```
"_countTotal": 6025,
"_countQuery": 6025,
"_skip": 0,
"_limit": null,
"_cached": false,
"_extra": {
    "stats": {
        "writesExecuted": 0,
        "writesIgnored": 0,
        "scannedFull": 9464,
        "scannedIndex": 0,
        "filtered": 275283,
        "httpRequests": 0,
        "fullCount": 9464,
        "executionTime": 1.8309500999748707,
        "peakMemoryUsage": 11007878
    },
    "warnings": []
},
"_current": 0,
"_stop": 6025
}

```
__Problem__:

1. Records retrieved by Foxx is always lesser (~80% to 40%) than count available in web interface
2. The result of query is array of objects. When result from FOXX is examined, it was noted that, "null" had been replaced for empty array ( [] ) on random basis for few of nodes.

__Expected result__:
Records retrieved by Foxx should match the total count fetched in Arango web interface (both in count and node content)

__Additional Info__:
Note: The query worked fine on Arango v3.2, 3.3 and 3.6
We have recently upgraded from Arango v3.2.8 (MMFiles) to Arango 3.7.15 (RocksDB). Upgrade was on done on a new VM and data set-up has been redone on new machine.

### PR DESCRIPTION
**Pull request by markuspf**
### Scope & Purpose

Fix BTS-673. 

Backport to 3.7 fixes #15107.

- [X] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [ ] Backport for 3.9: *(Please link PR)*
- [ ] Backport for 3.8: *(Please link PR)*
- [ ] Backport for 3.7: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket number:
- [ ] Design document: 

### Testing & Verification

*(Please pick either of the following options)*

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [ ] The behavior in this PR was *manually tested*
- [X] This change is already covered by existing tests, such as *(please describe tests)*.
- [X] This PR adds tests that were used to verify all changes:
  - [X] Added new C++ **Unit tests**
  - [X] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

Link to Jenkins PR run:

### Documentation

> All new features should be accompanied by corresponding documentation. 
> Bugs and features should furthermore be documented in the CHANGELOG so that
> support, end users, and other developers have a concise overview. 

- [ ] Added entry to *Release Notes* 
- [ ] Added a new section in the *Manual* 
- [ ] Added a new section in the *HTTP API* 
- [ ] Added *Swagger examples* for the HTTP API  
- [ ] Updated license information in *LICENSES-OTHER-COMPONENTS.md* for 3rd party libraries

### CODE REVIEW

File: arangod/Aql/ExecutionBlockImpl.cpp [hunk 1]
```diff
@@ -1132,6 +1137,9 @@ auto ExecutionBlockImpl<SubqueryEndExecutor>::shadowRowForwarding(
   _outputItemRow->advanceRow();
   // The stack in used here contains all calls for within the subquery.
   // Hence any inbound subquery needs to be counted on its level
+
+  // NOTE MCHACKI: I think this call is also off by one and needs to be
+  // getDepth() - 1
```
Comment (mchacki) [inline arangod/Aql/ExecutionBlockImpl.cpp:1142]:
```suggestion
```
This NOTE is simply not correct

File: tests/Aql/SubqueryEndExecutorTest.cpp [hunk 2]
```diff
@@ -43,64 +37,127 @@ using namespace arangodb::basics;
...
+  size_t subQuerySoftLimit = 10;
+  callStack.pushCall(AqlCallList{
+      AqlCall{0, false, subQuerySoftLimit, AqlCall::LimitType::SOFT},
+      AqlCall{0, false, subQuerySoftLimit, AqlCall::LimitType::SOFT}});
+  size_t numCalls = 0;
+
+  dependency.setExecuteEnterHook(
+      [&numCalls, mainQuerySoftLimit,
+       subQuerySoftLimit](AqlCallStack const &stack) {
+        LOG_DEVEL << stack.toString();
```
Comment (mchacki) [inline tests/Aql/SubqueryEndExecutorTest.cpp:137]:
```suggestion
```

**Review by mchacki — CHANGES_REQUESTED** [review]
Technical all good,
two leftovers that should be removed.

However please fix the formatting, it seems the position of `&` and `*` signs have changed in the touched files.

**Review by mchacki — APPROVED** [review]
LGTM
