### PR TITLE
[COR-50] Introduce thread-local leasers for builders and strings

### LINKED ISSUE #22158: Bug Report: ArangoDB 3.12.5 Crash When Running Specific Query
**Summary**
ArangoDB crashes after running a specific query several times
The query also fails to return results as expected.

**Environment:**
ArangoDB Version: 3.12.5
Storage Engine: RocksDB

**Database Structure**

The database contains the following collections and entities:
- Document Collection a
  Documents with keys: 1 to 4000

- Document Collection c
Documents with keys: 1 to 4000

- Edge Collection b
For each i in 1 to 4000, edge i connects:
from: a/{i}
to: c/{i}

**Steps to reproduce:**
run the query:
```
for node in @@col
  let x = (
    for n,e,p in 1..1 ANY node._id @@edge_col
      filter !is_null(e) && !is_null(e._from) && !is_null(e._to)
      filter PARSE_IDENTIFIER(e._from).collection in @_collections
      return n._id
    )
  
  
  filter length(x) > 0
  for n, ee, ppp in 1..1 ANY node._id @@edge_col
    filter PARSE_IDENTIFIER(ee._from).collection in @_collections && PARSE_IDENTIFIER(ee._to).collection in @_collections
    return ee
```
with the bind vars:
```
{
  "@col": "a",
  "@edge_col": "b",
  "_collections": [
    "a",
    "b",
    "c"
  ]
}
```

Query Result:
```Query error: AQL: Builder value not yet sealed [node #5: TraversalNode] (exception location: arangod/Aql/ExecutionBlockImpl.tpp:638). Please report this error to arangodb.com [node #6: CalculationNode] (exception location: arangod/Aql/ExecutionBlockImpl.tpp:620). Please report this error to arangodb.com [node #7: FilterNode] (exception location: arangod/Aql/ExecutionBlockImpl.tpp:620). Please report this error to arangodb.com [node #23: SubqueryEndNode] (exception location: arangod/Aql/ExecutionBlockImpl.tpp:620). Please report this error to arangodb.com [node #13: CalculationNode] (exception location: arangod/Aql/ExecutionBlockImpl.tpp:2690). Please report this error to arangodb.com [node #13: CalculationNode] (exception location: arangod/Aql/ExecutionBlockImpl.tpp:620). Please report this error to arangodb.com [node #14: FilterNode] (exception location: arangod/Aql/ExecutionBlockImpl.tpp:2690). Please report this error to arangodb.com [node #14: FilterNode] (exception location: arangod/Aql/ExecutionBlockImpl.tpp:620). Please report this error to arangodb.com [node #16: TraversalNode] (exception location: arangod/Aql/ExecutionBlockImpl.tpp:2690). Please report this error to arangodb.com [node #16: TraversalNode] (exception location: arangod/Aql/ExecutionBlockImpl.tpp:620). Please report this error to arangodb.com [node #17: CalculationNode] (exception location: arangod/Aql/ExecutionBlockImpl.tpp:620). Please report this error to arangodb.com [node #18: FilterNode] (exception location: arangod/Aql/ExecutionBlockImpl.tpp:620). Please report this error to arangodb.com [node #19: ReturnNode] (exception location: arangod/Aql/ExecutionBlockImpl.tpp:620). Please report this error to arangodb.com (while executing) (exception location: arangod/RestHandler/RestCursorHandler.cpp:306). Please report this error to arangodb.com```

### PR DESCRIPTION
**Pull request by markuspf**
### Scope & Purpose

Introduces thread-local leasers for velocypack::Builder and std::string.

This also addresses a problem with `async-prefetch` where builders and strings were leased through the transaction context, which is not meant to be acceessed concurrently.

- [x] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

Fixes #22158 and other issues with `async-prefetch`

---

> [!NOTE]
> Introduce thread-local leasers for Builder and std::string and refactor transaction leasers to use them, fixing async-prefetch concurrency issues and adding targeted tests.
> 
> - **Basics**:
>   - **New `ThreadLocalLeaser`**: Add `Basics/ThreadLocalLeaser.h` with thread-local pooling for reusable objects; typedefs `ThreadLocalBuilderLeaser` and `ThreadLocalStringLeaser`.
>   - **Tests**: Add `ThreadLocalLeaserTest.cpp` covering leasing, stash behavior, moves, and cross-thread handoff.
> - **Transaction**:
>   - **Refactor leasers**: `transaction::StringLeaser` and `transaction::BuilderLeaser` now use `ThreadLocal*Leaser` (`release/acquire/get`); remove context-based leasing/destructors/clear/steal.
>   - **Integrations**: Update usages in `Helpers.cpp/.h`, `Methods.cpp` (drop explicit `_replicationData.clear()`), and helpers to new APIs.
> - **Mocks/Tests**:
>   - Update `tests/Mocks/PhysicalCollectionMock.cpp` to use `builder.release()`.
>   - Add JS regression test `aql-async-prefetch-leaser-reuse.js` to stress async-prefetch concurrency.
> - **Changelog**:
>   - Note fix for concurrent reuse of builders/strings with async-prefetch.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit c0d55909056c3015ee7e73c26a96a1cd20d2c56f. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by markuspf** [comment]
Should add a test that at least tickles TSAN when run.

File: lib/Basics/ThreadLocalLeaser.h [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+constexpr auto max_leasees_per_thread = size_t{128};
+}
+
+namespace arangodb {
+
+template<typename T>
+struct ThreadLocalLeaser {
+  struct Lease {
+    ~Lease() {
+      // put builder on builders vector unless capacity is reached
```
Comment (mpoeter) [inline lib/Basics/ThreadLocalLeaser.h]: Remove this comment or move it to appropriate place (returnLease)

File: lib/Basics/ThreadLocalLeaser.h [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+      if (_leasee != nullptr) {
+        current.returnLeasee(std::move(_leasee));
+      }
+    }
+    Lease(Lease&&) = default;
+    auto operator=(Lease&&) -> Lease& = default;
+
+    friend struct ThreadLocalLeaser;
+
+    auto leasee() const -> T* { return _leasee.get(); }
```
Comment (mpoeter) [inline lib/Basics/ThreadLocalLeaser.h]: Should we just call it `get`?

**Comment by markuspf** [comment]
Should also measure performance implications.

At the moment there is only a very small number of leasable builders/string available per thread, as opposed to the previously unbounded number *per transaction*.

File: lib/Basics/ThreadLocalLeaser.h [hunk 3]
```diff
@@ -0,0 +1,103 @@
...
+      return Lease(std::move(leasee));
+    } else {
+      return Lease(std::make_unique<T>());
+    }
+  }
+
+  static auto stashSize() noexcept -> size_t { return current._stash.size(); }
+  static constexpr auto maxStashedPerThread = size_t{128};
+  static thread_local ThreadLocalLeaser current;
+  static auto lease() -> Lease { return current.doLease(); }
```
Comment (mpoeter) [inline lib/Basics/ThreadLocalLeaser.h]: Given that we have the static `lease` and `stashSize` functions, I think we can make `current` and `doLease` private.

File: lib/Basics/ThreadLocalLeaser.h [hunk 4]
```diff
@@ -0,0 +1,103 @@
...
+    }
+    Lease(Lease&&) = default;
+    auto operator=(Lease&&) -> Lease& = default;
+
+    friend struct ThreadLocalLeaser;
+
+    auto get() const noexcept -> T* { return _object.get(); }
+    auto operator->() const noexcept -> T* { return get(); }
+    auto operator*() noexcept -> T& { return *get(); }
+    auto operator*() const noexcept -> T& { return *get(); }
```
Comment (mpoeter) [inline lib/Basics/ThreadLocalLeaser.h]: Should the const versions return const reference/pointers?
In that case we also have to add more non-const versions.

File: tests/Basics/ThreadLocalLeaserTest.cpp [hunk 5]
```diff
@@ -0,0 +1,190 @@
...
+    b->add(VPackValue("Hello, world"));
+    ASSERT_FALSE(b->isEmpty());
+
+    builder = b.get();
+  }
+  // here the lease b has been dropped and the builder is returned to
+  // the stash
+
+  auto c = ThreadLocalBuilderLeaser::lease();
+  ASSERT_EQ(c.get(), builder);
```
Comment (mpoeter) [inline tests/Basics/ThreadLocalLeaserTest.cpp:84]: Might want to also check the stashSize before and after the call to `lease` (with `EXPECT_EQ` since this check should not prematurely abort the test).

File: tests/Basics/ThreadLocalLeaserTest.cpp [hunk 6]
```diff
@@ -0,0 +1,190 @@
...
+
+    auto c = std::move(b);
+    ASSERT_EQ(b.get(), nullptr);
+    ASSERT_NE(c.get(), nullptr);
+    builder = c.get();
+  }
+
+  auto b = ThreadLocalBuilderLeaser::lease();
+  ASSERT_EQ(b.get(), builder);
+}
```
Comment (mpoeter) [inline tests/Basics/ThreadLocalLeaserTest.cpp:120]: Might also want to check the stashSize here - in particular also to check that the moved-from lease does not push anything.

File: tests/Basics/ThreadLocalLeaserTest.cpp [hunk 7]
```diff
@@ -0,0 +1,190 @@
...
+      ASSERT_NE(c.get(), nullptr);
+    }
+    // Now c is dropped and should end up in this thread's stash
+
+    auto d = ThreadLocalBuilderLeaser::lease();
+    ASSERT_EQ(d.get(), builder);
+  });
+
+  threads.joinAll();
+}
```
Comment (mpoeter) [inline tests/Basics/ThreadLocalLeaserTest.cpp:144]: Would also check the stashSize of the main thread after the return.

File: tests/Basics/ThreadLocalLeaserTest.cpp [hunk 8]
```diff
@@ -0,0 +1,190 @@
...
+  {
+    auto leases = std::vector<ThreadLocalBuilderLeaser::Lease>{};
+    leases.reserve(ThreadLocalBuilderLeaser::maxStashedPerThread);
+    for (auto i = size_t{0}; i < ThreadLocalBuilderLeaser::maxStashedPerThread;
+         ++i) {
+      auto& it = leases.emplace_back(ThreadLocalBuilderLeaser::lease());
+      ASSERT_EQ(it.get(), lease_ptrs.back());
+      lease_ptrs.pop_back();
+    }
+  }
```
Comment (mpoeter) [inline tests/Basics/ThreadLocalLeaserTest.cpp:174]: This test gathers leases in a vector, and when the vector is destroyed all leases are implicitly returned. Then we check the order of the returned leases. But that means that we rely on the order in which the vector destroys the leases, and I don't know it this is clearly defined. Instead, I would perhaps manually pop the leases from the vector one by one in a clearly defined order.

File: tests/js/client/aql/aql-async-prefetch-leaser-reuse.js [hunk 9]
```diff
@@ -0,0 +1,100 @@
...
+  db._collection(colNameA).insert(averts);
+  db._collection(colNameC).insert(cverts);
+  db._collection(colNameB).insert(bedges);
+};
+
+////////////////////////////////////////////////////////////////////////////////
+/// @brief test suite
+////////////////////////////////////////////////////////////////////////////////
+
+function asyncPrefetchReuseTestSuite() {
```
Comment (mpoeter) [inline tests/js/client/aql/aql-async-prefetch-leaser-reuse.js:62]: Please add a comment that this is a regression test and include a reference to the original issue.

File: tests/Basics/ThreadLocalLeaserTest.cpp (hunk 6 above)
Comment (markuspf) [reply tests/Basics/ThreadLocalLeaserTest.cpp:120]: the test `testLeaseMovedOutOf` checks that a moved-out-of lease does not increase the stash size, whereas the test `testLeaseMovedOutOfReturned` asserts that if an object is moved between two leases and the second lease is dropped, it is then returned subsequently as a lease again.

Comment (markuspf) [reply tests/Basics/ThreadLocalLeaserTest.cpp:120]: Added an assertion so that after `b` and `c` go out of scope the stash only contains one lease (which is the one we assert to be getting back, then).

**Comment by markuspf** [comment]
For the record: simple performance tests did not show any effect of this change on performance.
