### PR TITLE
[3.6] Fix scoping error when COLLECT is used in a subquery

### LINKED ISSUE #10897: COLLECT without FOR loop leads to odd "variable assigned multiple times" error
## My Environment

* __ArangoDB Version__:        devel @ 847175ebc7ac4153b89b2d7a08f71cf69ae54d1d but also observed in current 3.5.4 build
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               default
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 18.04
* __Used Package__:              self-compiled

## Component, Query & Data

__Affected feature__:
AQL

__AQL query (if applicable)__:

```js
LET t = (COLLECT foo = anything RETURN true) RETURN true
```

## Steps to reproduce

1. Try to explain or execute above query
2. An unexpected error is raised: **variable 'foo' is assigned multiple times**

__Problem__:

```
db._query(`LET t = (COLLECT foo = anything RETURN true) RETURN true`)
JavaScript exception in file '/home/simran/oskar/work/ArangoDB/js/client/modules/@arangodb/arangosh.js' at 99,7: ArangoError 1511: AQL: variable 'foo' is assigned multiple times (while parsing)
!      throw error;
!      ^
stacktrace: ArangoError: AQL: variable 'foo' is assigned multiple times (while parsing)
    at Object.exports.checkRequestResult (/home/simran/oskar/work/ArangoDB/js/client/modules/@arangodb/arangosh.js:97:21)
    at ArangoStatement.execute (/home/simran/oskar/work/ArangoDB/js/client/modules/@arangodb/arango-statement.js:172:12)
    at Proxy.ArangoDatabase._query (/home/simran/oskar/work/ArangoDB/js/client/modules/@arangodb/arango-database.js:938:45)
    at <shell command>:1:4
```

__Expected result__:

It does not complain about the use of an unknown variable `anything`, but more importantly, it accepts a query where COLLECT is used without FOR loop **in a subquery** and raises a weird error. If you run `COLLECT foo = anything RETURN foo` for comparison, it will error out because `anything` is not defined, and `COLLECT foo = 42 RETURN foo` simply returns 42.

I guess it should behave the same in a subquery, or COLLECT without FOR shouldn't be accepted if it can't be supported in subqueries.

### PR DESCRIPTION
**Pull request by markuspf**
Fixes #10897 (backport to 3.6)

### CODE REVIEW

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/8170/

File: tests/js/server/aql/aql-collect-subquery-scope-regression.js [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+
+////////////////////////////////////////////////////////////////////////////////
+/// @brief test regression with incorrect scoping of collect variable
+//         inside subquery
+////////////////////////////////////////////////////////////////////////////////
+
+    testSubqueryCollectScopeOk : function () {
+      const query = `LET t = (COLLECT foo = undefined RETURN true) RETURN true`;
+      try {
+      var actual = db._query(query);
```
Comment (jsteemann) [inline tests/js/server/aql/aql-collect-subquery-scope-regression.js]: please fix indentation in this function.

Comment (jsteemann) [reply tests/js/server/aql/aql-collect-subquery-scope-regression.js]: and please add `fail()` here, because that will make the test fail in case the expected exception is not thrown.

File: tests/js/server/aql/aql-collect-subquery-scope-regression.js [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+    setUpAll : function () {
+    },
+
+////////////////////////////////////////////////////////////////////////////////
+/// @brief tear down
+////////////////////////////////////////////////////////////////////////////////
+
+    tearDownAll : function () {
+    },
+
```
Comment (jsteemann) [inline tests/js/server/aql/aql-collect-subquery-scope-regression.js]: not necessary and can be removed

File: tests/js/server/aql/aql-collect-subquery-scope-regression.js [hunk 3]
```diff
@@ -0,0 +1,87 @@
...
+/// Copyright holder is triAGENS GmbH, Cologne, Germany
+///
+/// @author Markus Pfeiffer
+/// @author Copyright 2020, triAGENS GmbH, Cologne, Germany
+////////////////////////////////////////////////////////////////////////////////
+
+var jsunity = require("jsunity");
+var internal = require("internal");
+var errors = internal.errors;
+var db = require("@arangodb").db, indexId;
```
Comment (jsteemann) [inline tests/js/server/aql/aql-collect-subquery-scope-regression.js]: what's the purpose of `indexId`?

File: tests/js/server/aql/aql-collect-subquery-scope-regression.js [hunk 4]
```diff
@@ -0,0 +1,87 @@
...
+/// @brief test regression with incorrect scoping of collect variable
+//         inside subquery
+////////////////////////////////////////////////////////////////////////////////
+
+    testSubqueryCollectScopeOk : function () {
+      const query = `LET t = (COLLECT foo = undefined RETURN true) RETURN true`;
+      try {
+      var actual = db._query(query);
+      } catch(e) {
+        assertEqual(e.errorNum, 1203);
```
Comment (jsteemann) [inline tests/js/server/aql/aql-collect-subquery-scope-regression.js]: `1203` == `errors.ERROR_ARANGO_DATA_SOURCE_NOT_FOUND.code`

File: tests/js/server/aql/aql-collect-subquery-scope-regression.js [hunk 5]
```diff
@@ -0,0 +1,87 @@
...
+	assertEqual(e.errorMessage, "AQL: collection or view not found: undefined (while parsing)");
```
Comment (jsteemann) [inline tests/js/server/aql/aql-collect-subquery-scope-regression.js]: Let's not check for exact error messages, as they change from time to time. Checking the error code should already be enough.

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/8189/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/8191/

**Comment by markuspf** [comment]
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/8192/

**Comment by mchacki** [comment]
The changes requested have been addressed.
The Jenkins is failed in a unrelated area, this PR is mergeable.

**Comment by KVS85** [comment]
Tests blue except known unrelated `hot_backup` suite failure on Linux.
