### PR TITLE
Correctly handle development flag in upgrade

### LINKED ISSUE #12363: Upgrading Foxx app turn it into development mode
## My Environment

* __ArangoDB Version__:        3.6.5 (arangodb3_3.6.5-1_amd64.deb)
* __Storage Engine__:             RocksDB
* __Deployment Mode__:         Single Server
* __Deployment Strategy__:    ArangoDB Starter in Docker
* __Configuration__:               
* __Infrastructure__:               Ubuntu / Docker
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:        8G
* __Disks in use__:        HDD
* __Used Package__:            Docker - official Docker library

## Component, Query & Data

__Affected feature__:
Foxx-CLI

## Steps to reproduce

1. foxx upgrade -D test-projections -v /dependencies

__Problem__:

I installed my foxx app in production mode. Whe I upgrade it, it turns to development mode.

__Expected result__:

Stay in production mode

@pluma

### PR DESCRIPTION
**Pull request by pluma**
Fixes #12363.

### Scope & Purpose

This fixes a bug in the Foxx HTTP API where the `development` query parameter would not be parsed before being handed over to the Foxx Manager, resulting in `"false"` being interpreted as `true`.

- [x] :hankey: Bugfix 
- [ ] :pizza: New feature 
- [ ] :hammer: Refactoring 
- [x] :book: CHANGELOG entry made
- [x] :muscle: The behavior in this PR was *manually tested*
- [x] :computer: The behavior change can be verified via automatic tests

#### Backports:

- [x] No backports required
- [ ] Backports required for: *(Please specify versions)*

#### Related Information

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [x] GitHub issue / Jira ticket number: #12363 
- [ ] Design document: 

### Testing & Verification

*(Please pick either of the following options)*

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [x] This PR adds tests that were used to verify all changes:
  - [ ] Added **Regression Tests**
  - [ ] Added new C++ **Unit Tests**
  - [x] Added new **integration tests** (i.e. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)

Additionally:

- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

*(Include link to Jenkins run etc)*

### Documentation

> All new Features should be accompanied by corresponding documentation. 
> Bugs and features should furthermore be documented in the changelog so that
> developers and users have a concise overview. 

- [x] Added a *Changelog Entry* (referencing the corresponding public or internal issue number)
- [ ] Added entry to *Release Notes* 
- [ ] Added a new section in the *Manual* 
- [ ] Added a new section in the *HTTP API* 
- [ ] Added *Swagger examples* for the HTTP API  
- [ ] Updated license information in *LICENSES-OTHER-COMPONENTS.md* for 3rd party libraries

### CODE REVIEW

**Comment by pluma** [comment]
This is a longstanding bug that was discovered in 3.6 because `foxx-cli` defaults to setting the `development` flag to `false`. Omitting the flag does not trigger this bug, so I don't think this needs to be backported.

I will adjust the behavior of `foxx-cli` to not provide a default value for this flag, requiring users to explicitly pass `--development` or `--no-development` if they want to toggle development mode while performing an upgrade.

File: js/server/modules/@arangodb/foxx/manager.js [hunk 1]
```diff
@@ -838,20 +838,20 @@ function install (serviceInfo, mount, options = {}) {
...
-      development: options.development,
+      development: Boolean(options.development),
       configuration: options.configuration,
       dependencies: options.dependencies
     }
   });
   _install(tempService, tempPaths.tempBundlePath, {
-    setup: options.setup !== false,
-    force: options.force === true
+    setup: options.setup === undefined || Boolean(options.setup),
```
Comment (pluma) [inline js/server/modules/@arangodb/foxx/manager.js:853]: This avoids possible bugs if the user provides `0` or `1` instead of booleans, which the HTTP API technically allows although it is not explicitly documented AFAIK. `Boolean` coerces its argument to a boolean value.

**Review by dothebart — APPROVED** [review]

**Comment by dothebart** [comment]
has this been a side effect of the V8 upgrade?

**Comment by pluma** [comment]
@dothebart no, this was an oversight in the original development of the feature. It has continued to "work as designed". FWIW the `development` flag wasn't part of the official HTTP API but if present it is passed on to Foxx Manager, so it should be handled as expected rather than just passed down as a string.

Not sure if the docublock should be expanded to document this flag.

**Review by joerg84 — APPROVED** [review]

**Comment by pluma** [comment]
@joerg84 I thought this had been merged already. What do I need to do to get this merged?

**Comment by pluma** [comment]
pullrequestmerge

@joerg84 can we get this merged?

**Review by joerg84 — APPROVED** [review]
@pluma Do we need to backport this?

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13811/

File: CHANGELOG [hunk 2]
```diff
@@ -1,5 +1,6 @@
 devel
 -----
+* Fixed issue #12363: Foxx HTTP API upgrade/replace always enables devmode
```
Comment (jsteemann) [inline CHANGELOG:3]:
```suggestion

* Fixed issue #12363: Foxx HTTP API upgrade/replace always enables
  development mode.
```

**Review by jsteemann — APPROVED** [review]

**Comment by pluma** [comment]
Thanks.

@joerg84 We should probably backport this to 3.7 since the change was originally intended for 3.7, I think.

**Comment by jsteemann** [comment]
Tests blue
